//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidateIssuesGithub.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Github {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Github() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ValidateIssuesGithub.Properties.Github", typeof(Github).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIIEpAIBAAKCAQEAs8ZOZqm6T/T+VjKO2rY+rLC/qbHPVy5g3628nTTM+erWlmC8
        ///OV+2dyMCPUMb9oRlNTYKgYJUMGi+IPDkVaGwP6Hsz6fcZ9vIlH6eHrTBVzLYGy/B
        ///gSJe+1Am17cIIPpH0KaJjmNYFtb7oHtx4q2CkEbX4PwgJGIc2x32jLsTlELeUT7U
        ///ztQvrPANn5cJu57wouiSM0FR/SAELLkoqVHQA8jusgYuXIs5gjWWQVfz1kV2mdO8
        ///dGuU70X6+RIs0rrAMK608PY3AUbE97/4wykkcyPQKG/E2ZNYmq/8ZBumCfIHedzu
        ///sQ+epbgTY5FaHeVs5153EzP/Bh2JkPZR/kaWVwIDAQABAoIBAQCfqB9ax6PCfOcf
        ///8Fi0XqP8xCADefmVCIhaPjbDOvBLh8c52AFxxtIKrlm/xIjh/yTPBAaCjBduwqcQ
        ///JD/02NrpOEpTBVYWGrfhQS32QTtv0KTiSCBHKhpGgSFt9IxQlVYQNMb3Y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GITHUB_APP_PRIVATE_KEY {
            get {
                return ResourceManager.GetString("GITHUB_APP_PRIVATE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assssssss.
        /// </summary>
        internal static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
    }
}
